version: "3"
services:
  nginx:
    image: "nginx:1.18.0-alpine"
    container_name: "nginx"
    restart: "always"
    volumes:
      - "${FORSTREAM_HOME}/apps/forstream-configs/server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${FORSTREAM_HOME}/data/letsencrypt:/data/letsencrypt"
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
networks:
  default:
    external:
      name: "forstream"
